services:
  app:
    build: .
    container_name: wedding-site
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - websites

networks:
  websites:
    external: true
